### PR TITLE
Rename uuid2mac to xhyve-uuid2mac for safety

### PR DESCRIPTION
**Pull request by ailispaw**
But it may be unnecessary.

### CODE REVIEW

**Comment by nlf** [comment]
yeah.. probably a good thought. it's entirely possible that there's another uuid2mac utility out there somewhere, don't want to step on any toes.

**Comment by nlf** [comment]
here's a thought.. what if we change the hostname of the vm for each run of init and use the name field in `/var/db/dhcpd_leases` to determine which ip address is ours. then we wouldn't even need the uuid2mac util

**Comment by nlf** [comment]
upon further inspection, that thought may only be valid the first time the vm boots, which won't work.. we need a way to set the hostname earlier i think

**Comment by ailispaw** [comment]
Yeah. The init script of boot2docker executes dhcp before set hostname. https://github.com/boot2docker/boot2docker/blob/master/rootfs/rootfs/bootscript.sh

**Comment by nlf** [comment]
looks like we can pass `host=somename` in the kernel parameters to do this

**Comment by ailispaw** [comment]
Oh I did't know that. Is that a standard parameter of linux kernel?

**Comment by nlf** [comment]
it's a feature of tinycore linux, which boot2docker is based off of. see this doc for other flags it supports: http://tinycorelinux.net/faq.html

**Comment by ailispaw** [comment]
Oh, looks nice. Let's try.

**Comment by ailispaw** [comment]
It works!

**Comment by ailispaw** [comment]
But we have to make sure an unique hostname or cleanup `/var/db/dhcpd_leases` before another `dhyve init`.

**Comment by ailispaw** [comment]
Or fix UUID on every init.

**Comment by nlf** [comment]
I already change the UUID on init, so we just need some way of making sure that we're generating a unique hostname, which we can just guess something simple and grep the dhcpd leases to make sure it's not already there

**Comment by nlf** [comment]
i would say just use the UUID as the hostname, but that might be kind of ugly.. it would work though.

**Comment by nlf** [comment]
maybe like `dhyve-` and then the first four characters of the md5 hash of the uuid? i dunno, i'm making stuff up :)

**Comment by ailispaw** [comment]
Ah, UUID seems good enough, because boot2docker replaces the UUID hostname with "boot2docker" after dhcp.

**Comment by nlf** [comment]
oh well then, yeah use the uuid :)

**Comment by ailispaw** [comment]
So this PR is closing.

**Comment by ailispaw** [comment]
Oops. boot2docker wouldn't replace it.....

**Comment by nlf** [comment]
Ah ok, then let's try something like dhyve- and four random chars (trim the md5 of the uuid)

**Comment by ailispaw** [comment]
How about fixed UUID for dhyve?
It won't create another entry in `/var/db/dhcpd_leases` on init/up and there should be only one dhyve entry in it.

**Comment by ailispaw** [comment]
And also it doesn't waste ip addresses.

**Comment by nlf** [comment]
That would work for now, but in the future I planned on allowing it to create more than one vm.. I haven't decided if that would be useful enough to move forward with or not yet, though.

I think it makes sense to go ahead and just hard code the hostname as `dhyve` and use a fixed UUID for now, and we can always switch it to be dynamic later.

**Comment by ailispaw** [comment]
I agree with that for now.
And I'm thinking about multiple VMs for clustering as well.

**Comment by nlf** [comment]
We can make multiple vms work easily enough by requiring the user to pass a hostname at creation time, so yeah I feel good about just hard coding it for now.

**Comment by ailispaw** [comment]
Sounds good to me.

**Pull request closed without merging**
