### PR TITLE
A tiny correction of #1

### PR DESCRIPTION
**Pull request by ailispaw**

### CODE REVIEW

**Comment by nlf** [comment]
Thanks! Also thanks for the inspiration, and the uuid2mac utility. I can honestly say this project wouldn't have happened without you

**Comment by ailispaw** [comment]
@nlf thanks for your great script. It inspires me as well. And I was thinking my next step would be this sort of project.

**Comment by nlf** [comment]
I'd be more than happy to add you to this repo and collaborate with you on continuing this project, if you're interested

**Comment by ailispaw** [comment]
Of course I'm!

**Comment by nlf** [comment]
You're added :)

**Comment by ailispaw** [comment]
Thanks ;)

**Pull request merged**
