### PR TITLE
update to use dhyveos, closes #12

### LINKED ISSUE #12: update to use dhyve-os
looks like this will still require a custom build

### PR DESCRIPTION
**Pull request by nlf**

### CODE REVIEW

**Comment by nlf** [comment]
@ailispaw take a look and let me know what you think

**Comment by ailispaw** [comment]
I will try it.

**Comment by ailispaw** [comment]
It works great.

I think we need to organize the terms, vm and os a bit.

**Comment by nlf** [comment]
i agree, a lot of the script needs to be refactored

 terminology is bad and there's a lot of repetition.

**Comment by ailispaw** [comment]
Ooops. `dhyve down` is working?

**Comment by nlf** [comment]
fixed

**Comment by ailispaw** [comment]
Confirmed.

**Comment by ailispaw** [comment]
But `kill <pid>` should work with acpid in dhyveos.
And also I have experienced `dhyve ssh` and then `sudo halt` will hang up there.

**Comment by nlf** [comment]
yeah, it's strange that acpid isn't working right. i'll see if i can figure out why.

**Comment by nlf** [comment]
misconfiguration in the kernel, i think. rebuilding now to test.

**Comment by nlf** [comment]
fixed in dhyve-os, going to go ahead and merge this (but not tagging as a release yet until we close a few more issues)

**Comment by ailispaw** [comment]
Now we can revert `vm_down` to use `kill`.

**Comment by nlf** [comment]
potentially we'll just be using launchd soon :)

**Pull request merged**
