### PR TITLE
cleanup error messages, add more checking

### PR DESCRIPTION
**Pull request by nlf**
just trying to be more consistent and helpful with error messages

### CODE REVIEW

**Comment by nlf** [comment]
just needs a quick once over when you have a chance @ailispaw

**Comment by ailispaw** [comment]
Let me see.

**Comment by ailispaw** [comment]
I think `vm_env ()` needs `check_vm_running` as well.

**Comment by ailispaw** [comment]
`check_vm_running` should include `check_vm_exists`, too.
And then,

```
check_vm_exists
check_vm_running
```

is going to be just `check_vm_running`.
How do you think?

**Comment by ailispaw** [comment]
Are `status=$(check_vm_running)` lines needed?
`check_vm_running` seems to return nothing.

**Comment by nlf** [comment]
I left `check_vm_running` off of `vm_env` because technically the vm just has to have been started once for the `vm_env` function to succeed, since all it does is search the `dhcpd_leases` file.

I also considered embedding `check_vm_exists` into `check_vm_running` because there are situations where i need more flexibility. In `vm_status` for example, it's an error if the vm doesn't exist at all, but we can print information whether it's running or not.

I could have different exit codes for if the failure is because of the vm not existing vs. the vm not running though to make that work. I just wasn't sure if it was worth it or not, honestly.

**Comment by nlf** [comment]
trapping the output isn't really needed, i just need to run it in a sub-shell so a failure doesn't cause the whole script to end

**Comment by ailispaw** [comment]
I see. Thanks for the explanations.
LGTM now.

**Comment by nlf** [comment]
awesome. i want to bump the boot2docker to 1.7.1 then we can release a 1.1.0 of dhyve i think

**Comment by ailispaw** [comment]
Sorry for this late reply.
Why don't you use `return` instead of `exit` in the `check_vm_running`?

**Comment by nlf** [comment]
because those are unrecoverable errors and the script should exit immediately if they fail

**Pull request merged**
