### PR TITLE
flesh out update/upgrade commands, for #8

### PR DESCRIPTION
**Pull request by nlf**

### CODE REVIEW

**Comment by nlf** [comment]
@ailispaw i'd love if you'd give this a once over before i merge it

**Comment by ailispaw** [comment]
Hi @nlf , let me see.

**Comment by ailispaw** [comment]
I got an error message.

> dhyve: line 90: pcregrep: command not found

**Comment by nlf** [comment]
dang.. i was hoping it was part of a normal osx install, but i guess not. i'll have to replace that bit with awk or sed

**Comment by nlf** [comment]
ok, swapped for awk, should work now

**Comment by ailispaw** [comment]
`~/.dhyve/dhyve.version` doesn't work well after manual install (make install).
I think the version should be embedded in the dhyve script.
What do you think?

**Comment by nlf** [comment]
yeah, that's probably a cleaner solution anyway.. i'll tweak to put it in a comment in the script itself

**Comment by ailispaw** [comment]
FYI: I found https://github.com/cloudflare/semver_bash and it may be good for version handling.

**Comment by ailispaw** [comment]
It might be too much for now though.

**Comment by nlf** [comment]
ok, dhyve version now embedded in the script directly.

i agree that semver parsing might be nice in the future, but for now it does feel like overkill.

it would be neat to print out some sort of abbreviated changelog or release notes when updating too, but that's another future feature i think.

**Comment by ailispaw** [comment]
LGTM :+1:

**Pull request merged**
